version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  # 追記
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - pma-session-store:/sessions

  # Node.js
  node:
    image: node:lts-alpine
    working_dir: /opt/laravel                # ワーキングディレクトリをLaravelのルートディレクトリにします。
    command: ["npm", "run", "watch-poll"]    # `docker-compose up -d`実行時のコマンドを`npm run watch-poll`にします。
    volumes:
      # npmのキャッシュファイル
      - npm-cache:/root/.mpm        
      # Laravelのソースファイル
      - ../laravel:/opt/laravel




volumes:
   # 追記
  pma-session-store:

  db-store:

  # volumes:
  npm-cache:
    driver: local